apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-ai
  namespace: default
  labels:
    app: estate-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estate-ai
  template:
    metadata:
      labels:
        app: estate-ai
    spec:
      containers:
      - name: estate-ai
        image: 869935091548.dkr.ecr.ap-northeast-2.amazonaws.com/estate-ai:latest
        command: ["python", "main.py", "web"]
        ports:
        - containerPort: 8000
        env:
        - name: CELERY_BROKER
          value: "redis://redis-service:6379/0"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: database-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: openai-api-key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: estate-ai-service
  namespace: default
spec:
  selector:
    app: estate-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP