apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-ai-worker
  namespace: default
  labels:
    app: estate-ai-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estate-ai-worker
  template:
    metadata:
      labels:
        app: estate-ai-worker
    spec:
      containers:
      - name: estate-ai-worker
        image: 869935091548.dkr.ecr.ap-northeast-2.amazonaws.com/estate-ai:latest
        command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER
          value: "redis://redis-service:6379/0"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: sentry-dsn
        envFrom:
        - configMapRef:
            name: estate-ai-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"