apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-etl
  namespace: default
  labels:
    app: estate-etl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estate-etl
  template:
    metadata:
      labels:
        app: estate-etl
    spec:
      containers:
      - name: estate-etl
        image: 869935091548.dkr.ecr.ap-northeast-2.amazonaws.com/estate-etl:latest
        ports:
        - containerPort: 8000
        env:
        - name: CELERY_BROKER
          value: "redis://redis-service:6379/0"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: estate-etl-service
  namespace: default
spec:
  selector:
    app: estate-etl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-etl-worker
  namespace: default
  labels:
    app: estate-etl-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estate-etl-worker
  template:
    metadata:
      labels:
        app: estate-etl-worker
    spec:
      containers:
      - name: estate-etl-worker
        image: 869935091548.dkr.ecr.ap-northeast-2.amazonaws.com/estate-etl:latest
        command: ["celery", "-A", "services.etl.main", "worker", "--loglevel=info", "--concurrency=4"]
        env:
        - name: CELERY_BROKER
          value: "redis://redis-service:6379/0"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-etl-scheduler
  namespace: default
  labels:
    app: estate-etl-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estate-etl-scheduler
  template:
    metadata:
      labels:
        app: estate-etl-scheduler
    spec:
      containers:
      - name: estate-etl-scheduler
        image: 869935091548.dkr.ecr.ap-northeast-2.amazonaws.com/estate-etl:latest
        command: ["celery", "-A", "services.etl.main", "beat", "--loglevel=info"]
        env:
        - name: CELERY_BROKER
          value: "redis://redis-service:6379/0"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: estate-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"