
name: Deploy AI Service to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'services/ai/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # Replace with your region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: estate-ai
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG services/ai
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name estate-eks-cluster --region ap-northeast-2

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/ai-configmap.yaml
          kubectl apply -f k8s/ai-deployment.yaml
          kubectl apply -f k8s/ai-worker-deployment.yaml
          kubectl set image deployment/estate-ai estate-ai=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl set image deployment/estate-ai-worker estate-ai-worker=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/estate-ai
          kubectl rollout status deployment/estate-ai-worker
